### ISSUE TITLE
Uninformative error when affinity matrix creation throws bad_alloc

### ISSUE THREAD

**Issue by alexsmartens** [gadomski/cpd#104]
Hi Pete,

I have successfully installed the last version of CPD (on my laptop).
I've compiled a nonrigid program based on the rigid example, which you have with the distributive.

I've tested the nonrigid example on small artificial datasets first (10 points each) and on real datasets (2M points each). The first set of datasets was processed fine. But I got the error with the second set of datasets:

 ./cpd-nonrigid pt_in.txt pt_target.txt
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

What might be the problem? Have you had a chance to test the algorithm on large datasets?

**Comment by gadomski** [comment]
Yeah, two million points is most likely too much for the nonrigid. The [nonrigid registration](https://github.com/gadomski/cpd/blob/master/src/nonrigid.cpp#L23) [creates an `MxM` affinity matrix](https://github.com/gadomski/cpd/blob/master/src/utils.cpp#L79), where `M` is the number of points in the source dataset. The nonrigid lowrank transformation might be able to work with that many points, but it does not yet exist in this version of the library (see #57).

In my experience, I usually chop up datasets into ~10-20 thousand point chunks and run each chunk through CPD, then re-aggregate the result. I'd be very interested to hear about successful runs with larger datasets.

I'm going to keep this issue open because I should add better error reporting if the affinity matrix doesn't allocate — this is likely to be a common choke-point. Thanks for the report.
