### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by gadomski** [gadomski/cpd#23]
Can we? But really, *can* we?

**Comment by vipulraikar** [comment]
I have it compiled on Windows in VS15 (VS13 platform tools). There were a few issues though and I will address them when I have a more stable work-flow. 
To highlight the major one, I had trouble with the google-test framework so built it without any tests. Since the goal was to first just get everything working, I decided to skip them. I tried a quick console application in VS by including the headers. It worked, but doesn't say much. Ill keep posting as I make progress and give a more detailed feedback.

**Comment by gadomski** [comment]
@vipulraikar I'm most of the way to getting [gadomski/fgt](https://github.com/gadomski/fgt) up and running with full Windoze CI (gadomski/fgt#30). You can check out that pull request for some hints on how to get things working pretty on Windoze — in particular, the `gtest_force_shared_crt` option was critical to get tests both linking and running successfully.

If you do any cleanup work, please open a pull request with those changes, which I can then use as a starting branch to enable AppVeyor for this repository as well. :beers:
