### ISSUE TITLE
Where to find FGT library?

### ISSUE THREAD

**Issue by schuhschuh** [gadomski/cpd#32]
Hi Pete, nice implementation of the CPD algorithm. Just what I was looking for right now.
[Although I'd prefer non-GPL'd code as I intend to use it in a newer version of [IRTK](https://github.com/BioMedIA/IRTK) which will be released under BSD].

Trying to build the library, I was wondering where to find the FGT code ? You have documented all really well in the README, but this detail seems to be missing.

**Comment by gadomski** [comment]
Hi @schuhschuh, glad you find it useful. FGT is under development so (per usual) the CPD README lags the real world. https://github.com/gadomski/fgt. And yes I agree GPL2 is less than ideal, but since I'm doing a derivative work I have to respect the original license.

I expect both FGT and CPD to settle into a stable-ish state (for some value of stable) within the next month, as I plan on generating a bit of churn for the next few weeks. I'll do my best to keep both **master**s in sync and passing tests, though.

And of course, issues/pull requests quite welcome :beer:. Good luck!
