### ISSUE TITLE
gflags_SHARED and gflags_NOTHREADS options

### ISSUE THREAD

**Issue by schuhschuh** [gadomski/cpd#34]
I just wanted to let you know that I have taken your use of the gflags library as an example for two new options added to the ```gflags-config.cmake``` file. The recommended use is documented [here](https://gflags.github.io/gflags/#cmake). It will be part of the gflags 2.2.0 release version.

**Comment by gadomski** [comment]
@schuhschuh thanks for the heads up. I tested out `${gflags_LIBRARIES}` with gflags **master** against cpd and things seemed to work as expected. :+1: to the change.

As an aside, have you played with CMake's exported targets at all? I'm using them in **cpd** and **fgt**, and it seems (to me) to be pretty handy. It gives downstream projects a single name to use when linking to your library, regardless of the compiled characteristics of your library (shared/static, threaded, etc). Just something I've been experimenting with lately...

**Comment by schuhschuh** [comment]
Glad it worked. I have not modified the exported targets other than setting the INTERFACE_INCLUDE_DIRECTORIES properly on the (imported) targets which is a newer CMake feature. But it seemed you were using this before from some package generated maybe by somebody else ? Because I couldn't see a "include_directories(${flags_INCLUDE_DIR})" in your CMakeLists.txt which would have been required before the recent changes on master.

I haven't yet figured out how I can have an alias "gflags" import target given the different variants. Therefore the use of the gflags_LIBRARIES variable. It would probably be an option to simply create such default variant import target and copy the relevant properties from the respective ```${gflags_LIBRARIES}``` import target.

**Comment by gadomski** [comment]
Well, it turns out I [wasn't explicitly including the gflags include directory](https://github.com/gadomski/cpd/commit/4c49a88cfa3d24451835b5bce9c6fc3e2d07ead5), so I fixed that — thanks :-). Things were just working locally (and on Travis) b/c gflags was living alongside other dependencies.

Hm, yeah, re: target variants, I'm not sure. I wonder if [object libraries](http://www.cmake.org/Wiki/CMake/Tutorials/Object_Library) could help, since you currently seem to be set up to create a bunch of different flavors of library depending on the CMake configuration. Create a bunch of object libraries then use one (or more) of those object libraries to create the `gflags` target. Maybe? Just spitballin'...never used object libraries myself, just read about them.

**Comment by schuhschuh** [comment]
I've added a "gflags" target by copying the relevant properties from the respective import target of the specific flavor selected (cf. https://github.com/gflags/gflags/issues/110). With the master branch (or gflags 2.2.0), you will no longer need to explicitly add the gflags_INCLUDE_DIR (though it would still be needed in case somebody has an older version installed).
